### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by boris191055** [tomwenseleers/export#30] opened 2020-06-07 12:01 UTC
Hi
I am trying to install export from github to Rstudio based on R 4.0 and this is what I got (below). Any help will be greatly appreciated because export is an extremely useful package.

> devtools::install_github("tomwenseleers/export")
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
Downloading GitHub repo tomwenseleers/export@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                               
2: CRAN packages only                
3: None                              
4: httpuv (1.5.3.1 -> 1.5.4  ) [CRAN]
5: later  (1.0.0   -> 1.1.0.1) [CRAN]
6: vctrs  (0.3.0   -> 0.3.1  ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\Owner\AppData\Local\Temp\RtmpWA1TdW\remotes381826937dd\tomwenseleers-export-269abaf/DESCRIPTION' (442ms)
-  preparing 'export':
√  checking DESCRIPTION meta-information ... 
-  excluding invalid files
   Subdirectory 'R' contains invalid file names:
     'export' 'export.rdb' 'export.rdx'
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'export_0.2.2.9001.tar.gz'
   
Installing package into ‘C:/Users/Owner/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'export' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'export'
    finding HTML links ... done
    graph2bitmap                            html  
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/graph2bitmap.Rd:64: file link 'tiff' in package 'grDevices' does not exist and so has been treated as a topic
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/graph2bitmap.Rd:64: file link 'jpeg' in package 'grDevices' does not exist and so has been treated as a topic
    graph2office                            html  
    graph2vector                            html  
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/graph2vector.Rd:68: file link 'svg' in package 'grDevices' does not exist and so has been treated as a topic
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/graph2vector.Rd:68: file link 'cairo_pdf' in package 'grDevices' does not exist and so has been treated as a topic
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/graph2vector.Rd:68: file link 'cairo_ps' in package 'grDevices' does not exist and so has been treated as a topic
    rgl2bitmap                              html  
    table2office                            html  
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/table2office.Rd:69: file link 'tidy' in package 'broom' does not exist and so has been treated as a topic
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/table2office.Rd:71: file link 'tidy' in package 'broom' does not exist and so has been treated as a topic
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/table2office.Rd:105: file link 'tidy' in package 'broom' does not exist and so has been treated as a topic
    table2spreadsheet                       html  
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/table2spreadsheet.Rd:61: file link 'tidy' in package 'broom' does not exist and so has been treated as a topic
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/table2spreadsheet.Rd:63: file link 'tidy' in package 'broom' does not exist and so has been treated as a topic
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/table2spreadsheet.Rd:97: file link 'tidy' in package 'broom' does not exist and so has been treated as a topic
    table2tex                               html  
Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpElaXyQ/R.INSTALL8c042841a65/export/man/table2tex.Rd:52: file link 'tidy' in package 'broom' does not exist and so has been treated as a topic
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (export)
> 

The command graph2ppt works though

**Comment by cvanderaa** [comment] 2020-06-08 10:04
Thanks for using our package! This is an issue we are also experiencing and we will be working on as soon as possible.

**Comment by cvanderaa** [comment] 2020-06-29 08:13
So, apparently the warnings occur only on Windows, see [here](https://github.com/r-lib/roxygen2/issues/707) for background. 

Basically, we've put some links to other packages using for example `\link[broom]{tidy}`. During installation, the help **file** called `tidy.Rd` will be searched for in the `broom` package. Since it does not exist, the builder throws a warning. I replaced those problematic links with `\link{tidy}` which should look up the `tidy` **topic** in any installed packages, see commit baa0b40.

@tomwenseleers @boris191055 Could check if you still have those warnings?

**Comment by boris191055** [comment] 2020-06-29 08:21
Thanks! What is the new version that needed to be downloaded and checked? BTW, the export package is still absent from the main CRAN depository.

**Comment by cvanderaa** [comment] 2020-06-29 08:25
The newest version on `GitHub` should work now. So you could install it using:

```r
devtools::install_github("tomwenseleers/export")
```

Indeed it is still absent from CRAN, we will submit a request this week.

**Comment by boris191055** [comment] 2020-06-29 08:38
I removed previously installed export and tried to install the new one.
Failed and got the following message:

package ‘backports’ successfully unpacked and MD5 sums checked
Error: Failed to install 'export' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘backports’
> remove.packages('backports')
Removing package from ‘C:/Users/Owner/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Error in remove.packages : there is no package called ‘backports’

**Comment by boris191055** [comment] 2020-06-29 08:41
Some update. I just removed "backports' manually from ‘C:/Users/Owner/Documents/R/win-library/4.0 then run 
devtools::install_github("tomwenseleers/export")

It seems this worked:
Here is what I got
> devtools::install_github("tomwenseleers/export")
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
Downloading GitHub repo tomwenseleers/export@master
Installing 1 packages: backports
Installing package into ‘C:/Users/Owner/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
          binary source needs_compilation
backports  1.1.7  1.1.8              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/backports_1.1.7.zip'
Content type 'application/zip' length 81641 bytes (79 KB)
downloaded 79 KB

package ‘backports’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Owner\AppData\Local\Temp\Rtmpo74yHw\downloaded_packages
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\Owner\AppData\Local\Temp\Rtmpo74yHw\remotes24884698718b\tomwenseleers-export-baa0b40/DESCRIPTION' ...
-  preparing 'export':
√  checking DESCRIPTION meta-information ... 
-  excluding invalid files
   Subdirectory 'R' contains invalid file names:
     'export' 'export.rdb' 'export.rdx'
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'export_0.2.2.9001.tar.gz'
   
Installing package into ‘C:/Users/Owner/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'export' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'export'
    finding HTML links ... done
    graph2bitmap                            html  
    graph2office                            html  
    graph2vector                            html  
    rgl2bitmap                              html  
    table2office                            html  
    finding level-2 HTML links ... done

Rd warning: C:/Users/Owner/AppData/Local/Temp/RtmpSYwlnT/R.INSTALL15b83a9d2b10/export/man/table2office.Rd:116: file link 'tidy' in package 'broom' does not exist and so has been treated as a topic
    table2spreadsheet                       html  
    table2tex                               html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (export)

**Comment by cvanderaa** [comment] 2020-06-29 08:45
Oops sorry, I missed one of the links. It should be fixed now. Thanks for testing!

**Comment by boris191055** [comment] 2020-06-29 08:55
And now this:
> devtools::install_github("tomwenseleers/export")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: there is no package called ‘backports’

**Comment by boris191055** [comment] 2020-06-29 09:01
Installed backports separately, then installed export again but this time did not update backports 
I mean, I entered empty line after:
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?
1: All                              
2: CRAN packages only               
3: None                             
4: backports (1.1.7 -> 1.1.8) [CRAN]
Enter one or more numbers, or an empty line to skip updates:

Seems worked

**Comment by LinusEngel** [comment] 2020-07-14 15:27
Hey there, 
I got the same trouble: first the installation process was stopped because of 'dplyr', then I omitted updates like boris191055 did, now installation stops at 'glue' package:

Error: Failed to install 'export' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘glue’

**Comment by cvanderaa** [comment] 2020-07-14 16:44
Hi @LinusEngel, 

It seems it is an error that has been converted from a warning. Did you set `options(warn = 2)`? 

It is really hard for me to reproduce your error. It might be that your `glue` package is installed in a write protected directory (e.g. somewhere in `ProgramFiles`), maybe try to locate `glue` that should be in one of the `.libPaths()` folders and delete it manually.

**Comment by LinusEngel** [comment] 2020-07-14 17:00
Hey there, 
I have set no options for the warnings. Should I?

I deleted 'glue' manually, which was just normally installed in the same documents/win-library folder like all other packages. Still getting an error referring to it:
> devtools::install_github("tomwenseleers/export")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
 error: there is no package called  ‘glue’

**Comment by cvanderaa** [comment] 2020-07-15 08:30
If `options()$warn` return 0 than no problem, but anyway there shouldn't be a warning. 

So now, it needs you to install back the `glue` package. There seems to be some confusion during the dependencies installation. I'm wondering if `BiocManager` could better handle this.

Before trying reinstalling `glue`, could you first try:

```r
BiocManager::install("tomwenseleers/export")
```

**Comment by LinusEngel** [comment] 2020-07-15 09:31
Sweet, that worked. And glue was installed again with the other dependencies; not sure though I know why it has been working now, but hopefully it helps you as well.

Thanks a lot!

**Closed** 2020-07-15 09:37 UTC
