### ISSUE TITLE
doc_parse_raw

### ISSUE THREAD

**Issue by guokai8** [tomwenseleers/export#16] opened 2018-11-09 19:45 UTC
Hi,
When I use graph2ppt on ubuntu system platform. It report the error:
```
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  StartTag: invalid element name [68]
```
And below is the details: 
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] export_0.2.2.9000

**Comment by tomwenseleers** [comment] 2018-11-09 19:48
Could you please provide a full reproducible example, so we can try on our end?

**Comment by guokai8** [comment] 2018-11-09 19:53
I just use very simple example:
```
library(export)
p<-plot(1:10)
graph2ppt(x=p,file="test.pptx")
```
I run this on ubuntu.

**Comment by tomwenseleers** [comment] 2018-11-09 20:13
Is the problem here not just that you are trying to pass a base R plot as an object, which is not possible? (You can only do that with ggplots)
So you would have to do instead
```
library(export)
plot(1:10)
graph2ppt(file="test.pptx")
```

Does that work OK for you?

**Comment by guokai8** [comment] 2018-11-09 20:18
I am sorry I don't have graphic interface on my server.

**Comment by guokai8** [comment] 2018-11-09 21:12
I try it but it doesn't work.
Thanks!

**Comment by tomwenseleers** [comment] 2018-11-10 07:18
And does exporting ggplots work for you?
E.g.
```
library(export)
library(ggplot2)
library(datasets)
x=qplot(Sepal.Length, Petal.Length, data = iris, 
        color = Species, size = Petal.Width, alpha = I(0.7))
graph2ppt(x=x, file="test.pptx")


```

**Comment by tomwenseleers** [comment] 2018-11-13 11:09
Could you try if this works on your configuration 
```
library(officer)
doc <- read_pptx()
doc <- add_slide(doc, "Title and Content", "Office Theme")
doc <- ph_with_vg_at(doc, code = barplot(1:5, col = 2:6),
  left = 1, top = 2, width = 6, height = 4)
print(doc, target = "vg.pptx")
```

If that one doesn't work without a graphics interface then I'm afraid `export `also won't work, since we rely on `officer `and `rvg`...

**Comment by guokai8** [comment] 2018-11-13 13:41
Hi,
I try it. it works. Thanks!

**Comment by tomwenseleers** [comment] 2018-11-13 13:46
So `officer `works, but the `export `package still doesn't work? Or does exporting `ggplots `work also in `export`?

**Comment by guokai8** [comment] 2018-11-13 13:49
Yes. ``` export ``` seems doesn't work but ```officer``` did. I haven't try ``` ggplots ```.

**Comment by tomwenseleers** [comment] 2018-11-13 13:58
OK I'll look into it then, because that means I should be able to fix `export `to make it work for this configuration... Would you know by any chance how to set up an R installation without a screen device?

**Comment by guokai8** [comment] 2018-11-13 14:10
It automatic setup on the server. Btw, the thing happened since I want build an shiny app("http://hurlab.med.und.edu/VennDetail/") by using your ```export``` package to export ppt and doc. Now it works. I found the reason also comes from ```UpSetR``` when I try to save the ```upset``` figure which always call ```grid.newpage``` function. I modified the ```upset``` code and used the ```ph_with_vg_at``` function.

**Comment by tomwenseleers** [comment] 2018-11-14 15:11
We just did an update to the github export version to make it work also for R users without a screen device. You can install it with 
`devtools::install_github("tomwenseleers/export")`
See if that works for you!

**Comment by guokai8** [comment] 2018-11-14 15:15
OK. I will try the new version. Thanks!

**Comment by tomwenseleers** [comment] 2018-11-19 08:47
And did it work for you in the end?

**Comment by jchap14** [comment] 2018-12-05 14:19
Hi Tom,

I am having this same issue. graph2ppt works in Rstudio when I export a dendrogram (or anything):

Example:
```
plot(hc.dend)
graph2ppt(file="dendrograms.pptx", append=F)
```

But returns the error below when I run it as an Rscript from the bash command line (no screen device):
```
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  :
  StartTag: invalid element name [68]
Calls: graph2ppt ... as_xml_document.character -> read_xml.raw -> doc_parse_raw
```

I re-installed the package using devtools::install_github("tomwenseleers/export") & that didn't fix it.

Thanks

**Comment by guokai8** [comment] 2018-12-05 14:21
Hi,
Sorry for the late reply. it seems the new version still not works.
Kai

**Comment by tomwenseleers** [comment] 2022-12-01 17:23
Can't reproduce this error on my side, so closing this for now. But feel free to reopen with a reproducible example in case problems would persist.

**Closed by tomwenseleers** 2022-12-01 17:23 UTC
