### ISSUE TITLE
Export was removed from CRAN.

### ISSUE THREAD

**Issue by lincj1994** [tomwenseleers/export#41] opened 2021-04-11 08:23 UTC
Hi, TOM.
Package 'export' was removed from cran. I wonder if you can upload it again.
Thanks.
Lin.

**Comment by cvanderaa** [comment] 2021-04-14 07:05
Hi @lincj1994 ,

Indeed, `export` was removed from CRAN because some changes in other packages broke our package. This is now fixed and we were planning to do it but I suddenly forgot about it... I will put `export` back to CRAN as soon as possible!

**Comment by agilebean** [comment] 2022-12-01 11:01
Hi @tomwenseleers,
any chance you can update your awesome package and bring it back to CRAN any time soon?
I think it's the best in the R world, so I really hope for an update...

**Comment by tomwenseleers** [comment] 2022-12-01 17:17
I would love to, but the CRAN check gives me some warning, which is the reason CRAN won't accept it as it is (only for Debian, not for Mac or Windows, and don't have that installed here; I only have Ubuntu here, where it doesn't give any warnings). So a bit tricky for me to resolve that - so unfortunately I don't quite know how I can get it accepted by CRAN or how I can resolve that issue.... If anyone would be able to figure that out I would be happy to accept a PR though! Or @cvanderaa - would you know what we need to do to get our package to pass the CRAN tests and get it back on CRAN? It would be nice indeed to have it back up there...

**Comment by cvanderaa** [comment] 2022-12-02 09:40
I can have a look at it this weekend. I'll try to set up a GitHub Action workflow to run the checks on different OS.

**Comment by cvanderaa** [comment] 2022-12-05 11:30
Hi @tomwenseleers, I set up the GHA for the different OS. I used a generic workflow for standard R check from the [ `rlib-actions` repo](https://github.com/r-lib/actions/tree/v2/examples#standard-ci-workflow).  Beside installing `xquartz` for macOS and setting RGL params, I didn't have to change anything and all checks passed. So, I believe the package is ready to be sent to CRAN :tada:

**Comment by tomwenseleers** [comment] 2022-12-05 20:55
Ha that's great @cvanderaa! Will you submit it, or would you like me to do it?

**Comment by tomwenseleers** [comment] 2022-12-05 22:30
Hmm - @cvanderaa - so I got the package back, apparently some NOTES.
package export_0.3.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/export_0.3.0_20221205_230938/Windows/00check.log>
Status: 1 NOTE :
"* checking CRAN incoming feasibility ... [9s] NOTE
Maintainer: 'Tom Wenseleers <tom.wenseleers@kuleuven.be>'

New submission

Package was archived on CRAN

CRAN repository db overrides:
  X-CRAN-Comment: Archived on 2020-02-11 as check problems were not
    corrected in time.

The Date field is over a month old."

Debian: <https://win-builder.r-project.org/incoming_pretest/export_0.3.0_20221205_230938/Debian/00check.log>
Status: 2 NOTE :
"NOTE
Maintainer: ‘Tom Wenseleers <tom.wenseleers@kuleuven.be>’

New submission

Package was archived on CRAN

CRAN repository db overrides:
  X-CRAN-Comment: Archived on 2020-02-11 as check problems were not
    corrected in time.

The Date field is over a month old."

Any idea what I should do about this? Or should I reply to them that this should be no problem?

**Comment by tomwenseleers** [comment] 2022-12-06 08:19
Hey @cvanderaa - I just got the package back, saying
"Flavor: r-devel-linux-x86_64-debian-gcc
Check: for detritus in the temp directory, Result: NOTE
   Found the following files/directories:
     'calibre_6.9.0_tmp_9r6xkapd' 'calibre_6.9.0_tmp__rujrznq'
     'calibre_6.9.0_tmp_dozypqjs' 'calibre_6.9.0_tmp_fp924pjj'
     'calibre_6.9.0_tmp_l3azsdjz' 'calibre_6.9.0_tmp_pfmb2i96'
     'calibre_6.9.0_tmp_vnqazp87' 'calibre_6.9.0_tmp_xcpm861s'

which suggests you open a web browser in non interactive mode.
Please always protect such call by if(interactive()).

Please fix and resubmit."

Do you have any thought how we have to fix that?

**Comment by cvanderaa** [comment] 2022-12-06 09:39
Ah, I had such files popping up locally as well, I thought I could ignore them. I'll try debugging this and keep you updated!

**Comment by tomwenseleers** [comment] 2022-12-06 11:04
If I try it on https://builder.r-hub.io/, selecting Debian under advanced it passes btw, https://builder.r-hub.io/status/export_0.3.0.tar.gz-1b2b07da115fd81bc89112bf2adbda8d. But presumably it doesn't check for those temporary files there... I think it may also be because they use a noninteractive session there I believe...

**Comment by cvanderaa** [comment] 2022-12-06 14:27
I added `if (interactive())` to a few examples that opened my browser when running `R CMD check .` locally. I hope this solves the issue :crossed_fingers:  I'll need some more time to see how we could run the examples with GHA in a non-iterative mode, so that these errors pop up on our side in a reproducible and automated fashion.

**Comment by tomwenseleers** [comment] 2022-12-06 21:50
Thanks Chris! Just uploaded it, and it passes the pre-checks OK now, so fingers crossed! Thanks again for the help!

**Comment by tomwenseleers** [comment] 2022-12-07 15:41
Still had to fix something minor in the documentation, but now CRAN informed me they accepted the package, so it should be back up again on CRAN soon!

**Closed** 2022-12-07 15:42 UTC
