### ISSUE TITLE
graph2ppt crashes with powerpoint open

### ISSUE THREAD

**Issue by ThomasR099** [tomwenseleers/export#46] opened 2022-04-05 17:30 UTC
Not entirely unexpected; having the PPT open and appending a slide to it crashes R.
Would there be a way to have the package check for open powerpoint windows before writing to the file?

**Comment by cvanderaa** [comment] 2022-07-28 08:50
Sorry for the late reply... Unfortunately, I don't have PPT and cannot reproduce the issue with LibreOffice Impress as it seems to cache the currently open session away from the actual pptx file. If meanwhile you could fix the issue, do not hesitate to make a pull request :wink:

**Comment by tomwenseleers** [comment] 2022-12-01 17:19
Yes, the only way to avoid that is to make sure that the file you try to work with isn't simultaneously open in PPT. No obvious way in which I can fix that unfortunately, so I'll close this issue for now...

**Closed by tomwenseleers** 2022-12-01 17:19 UTC
